let form = document.querySelector("#conversaction__form");
let commentsWrapper = document.querySelector(".comments__wrapper");
let currentDate = new Date().toLocaleDateString();

form.addEventListener("submit", (e) => {
  e.preventDefault();
  let name = e.target.name.value;
  let comment = e.target.comments.value;
  let comments = document.createElement("div");
  comments.classList.add("comment");
  let headerDiv = document.createElement("div");
  headerDiv.classList.add("comment__header");
  let img = document.createElement("img");
  img.setAttribute("src", "./assets/Images/Mohan-muruge.jpg");
  img.classList.add("avatar1");
  let commentUl = document.createElement("ul");
  commentUl.classList.add("comment__ul");
  let names = document.createElement("li");
  names.classList.add("comment__li");
  let Dates = document.createElement("li");
  let paragraph = document.createElement("p");
  paragraph.classList.add("comment__p");
  commentsWrapper.prepend(comments);
  comments.appendChild(headerDiv);
  headerDiv.appendChild(img);
  headerDiv.appendChild(commentUl);
  commentUl.appendChild(names).innerText = name;
  commentUl.appendChild(Dates).innerText = currentDate;
  comments.appendChild(paragraph).innerText = comment;
});
